// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DefaultFirebaseOptions have not been configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

    static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmGyTGVQ7fl2kP0bbOTRzOcywMmwBI800',
    appId: '1:783513830794:android:a01260ab5e5339d74fb473',
    messagingSenderId: '783513830794',
    projectId: 'mu-app-aa184',
    storageBucket: 'mu-app-aa184.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7v31LHm0vUET1g2q83xj7ib4puSFS5YA',
    appId: '1:783513830794:ios:9fc1f02b3caf58b34fb473',
    messagingSenderId: '783513830794',
    projectId: 'mu-app-aa184',
    storageBucket: 'mu-app-aa184.firebasestorage.app',
    iosBundleId: 'com.niyati.muapp2026',
  );
}